name: FastAPI run

on:
  pull_request:
  push:

jobs:
  fastapi-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn

    - name: Run FastAPI
      run: uvicorn main:app --host 0.0.0.0 --port 8000
